### ISSUE TITLE
Conflict of lptmr_isr with Entropy library

### ISSUE THREAD

**Issue by CZEMacLeod** [PaulStoffregen/Servo#2]
I am trying to use this library on a Teensy LC to control some servos (actually linear actuators but the `writeMicroseconds` function works perfectly for me without any angles involved).
I was unsure if this library or the `PWMServo` library was 'newer' but it looked like this had optimisations for the LC and supported direct setting the pulse width in microseconds which I needed.

I am also trying to use the `Entropy` library which also seems to define `lptmr_isr`.

Is there any way of getting these two libraries to play together nicely?

**Comment by PaulStoffregen** [comment]
No, sorry, not possible on Teensy LC.  They both can only use LPTMR on LC.  On Teensy 3.2, Servo uses PDB rather than LPTMR, so they can work together on 3.2.
